using Newtonsoft.Json;

namespace XmlParser.AutoGeneratedModels
{
    public class CatalogItem
    {
        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("item_number")]
        public string ItemNumber { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("size")]
        public List<Size> Size { get; set; }
    }
}
