using Newtonsoft.Json;

namespace XmlParser.AutoGeneratedModels
{
    public class Color
    {
        [JsonProperty("image")]
        public string Image { get; set; }

        [JsonProperty("#text")]
        public string Text { get; set; }
    }
}
