using Newtonsoft.Json;

namespace XmlParser.AutoGeneratedModels
{
    public class Size
    {
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("color_swatch")]
        public List<Color> ColorSwatch { get; set; }
    }
}
