using Newtonsoft.Json;
using XmlParser.AutoGeneratedModels;

namespace XmlParser.Tests
{
    [TestFixture]
    public class XmlParserTests
    {
        private readonly string path = "C:\\Users\\Max\\Source\\Repos\\XmlParser\\source.xml";

        private static Root GetCatalog
        {
            get
            {
                return new Root()
                {
                    catalog = new Catalog()
                    {
                        Product = new Product()
                        {
                            Description = "Cardigan Sweater",
                            ProductImage = "cardigan.jpg",
                            CatalogItem = new List<CatalogItem>()
                            {
                                new CatalogItem()
                                {
                                    Gender = "Men's",
                                    ItemNumber = "QWZ5671",
                                    Price = "39.95",
                                    Size = new List<Size>()
                                    {
                                        new Size()
                                        {
                                            Description = "Medium",
                                            ColorSwatch = new List<Color>()
                                            {
                                                new Color()
                                                {
                                                    Image = "red_cardigan.jpg",
                                                    Text = "Red"
                                                },
                                                new Color()
                                                {
                                                    Image = "burgundy_cardigan.jpg",
                                                    Text = "Burgundy"
                                                }
                                            }
                                        },
                                        new Size()
                                        {
                                            Description = "Large",
                                            ColorSwatch = new List<Color>()
                                            {
                                                new Color()
                                                {
                                                    Image = "red_cardigan.jpg",
                                                    Text = "Red"
                                                },
                                                new Color()
                                                {
                                                    Image = "burgundy_cardigan.jpg",
                                                    Text = "Burgundy"
                                                }
                                            }
                                        }
                                    }
                                },

                                new CatalogItem()
                                {
                                    Gender = "Women's",
                                    ItemNumber = "RRX9856",
                                    Price = "42.50",
                                    Size = new List<Size>()
                                    {
                                        new Size()
                                        {
                                            Description = "Small",
                                            ColorSwatch = new List<Color>()
                                            {
                                                new Color()
                                                {
                                                    Image = "red_cardigan.jpg",
                                                    Text = "Red"
                                                },
                                                new Color()
                                                {
                                                    Image = "navy_cardigan.jpg",
                                                    Text = "Navy"
                                                },
                                                new Color()
                                                {
                                                    Image = "burgundy_cardigan.jpg",
                                                    Text = "Burgundy"
                                                }
                                            }
                                        },
                                        new Size()
                                        {
                                            Description = "Medium",
                                            ColorSwatch = new List<Color>()
                                            {
                                                new Color()
                                                {
                                                    Image = "red_cardigan.jpg",
                                                    Text = "Red"
                                                },
                                                new Color()
                                                {
                                                    Image = "navy_cardigan.jpg",
                                                    Text = "Navy"
                                                },
                                                new Color()
                                                {
                                                    Image = "burgundy_cardigan.jpg",
                                                    Text = "Burgundy"
                                                },
                                                new Color()
                                                {
                                                    Image = "black_cardigan.jpg",
                                                    Text = "Black"
                                                }
                                            }
                                        },new Size()
                                        {
                                            Description = "Large",
                                            ColorSwatch = new List<Color>()
                                            {
                                                new Color()
                                                {
                                                    Image = "navy_cardigan.jpg",
                                                    Text = "Navy"
                                                },
                                                new Color()
                                                {
                                                    Image = "black_cardigan.jpg",
                                                    Text = "Black"
                                                }
                                            }
                                        },
                                        new Size()
                                        {
                                            Description = "Extra Large",
                                            ColorSwatch = new List<Color>()
                                            {
                                                new Color()
                                                {
                                                    Image = "burgundy_cardigan.jpg",
                                                    Text = "Burgundy"
                                                },
                                                new Color()
                                                {
                                                    Image = "black_cardigan.jpg",
                                                    Text = "Black"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                };
            }
        }

        [Test]
        public void Test1()
        {
            var result = BusinessLogic.XmlParser.ParseXmlFile<Root>(path);

            var correctJson = JsonConvert.SerializeObject(GetCatalog);
            var resultJson = JsonConvert.SerializeObject(result);

            Assert.That(correctJson, Is.EqualTo(resultJson));
        }
    }
}